### ISSUE TITLE
Can't open a file in the hex editor

### ISSUE THREAD

**Issue by fridtjof** [fudgepop01/kaitai_ide_vscode#1]
I opened the hex editor, right clicked a file (152 KB), and clicked "open file as hex". The hex editor does not react though, and keeps showing nothing.

Looking at the dev console shows this:

<img width="895" alt="grafik" src="https://user-images.githubusercontent.com/2780577/60694145-63276d00-9edd-11e9-9ca7-af6f49f1eb17.png">

I am running:

- macOS 10.14.5
- VSCode 1.36.0

Please tell me if I can provide any further useful information :)

Edit: After the context menu option did not work, I tried the same command from the command palette. Only from that did I get a notification saying that the command failed. In both cases, nothing happened in the hex editor though.

Edit 2: This is how the hex editor looks when opening any file:
<img width="522" alt="grafik" src="https://user-images.githubusercontent.com/2780577/60763241-86ceec80-a070-11e9-9b6a-40e2bc08c807.png">

**Comment by fudgepop01** [comment]
Hm, well that's new. Can I have the file that you tried to open? I'd like to take a look to see if I get the same result.
Another thing you could do to provide additional information is by using the "open webview developer tools" from the command palette and showing me the console output there. Thanks!

**Comment by fridtjof** [comment]
I am about to go to bed for today, but I'll do that really quick.

The file is from a game's assets, so I'll send it to you via email to avoid any (though unlikely) legal headaches.

Unfortunately, there is no console output at all in the webview developer console.

**Comment by fudgepop01** [comment]
Sounds good. I'll take a look!
from the output it _looks_ like for some reason fs.readFileSync isn't loading and interpreting the file properly.

As for the lack of any hex being viewed, try adjusting the horizontal size of the window or reducing the "bytes per line" value. I've yet to make the hex editor component properly responsive, so I suspect that the hex part of the editor is just hidden behind the settings panel.

---

Try installing the following through VSIX and then show me what the console says:
[kaitai-struct-vscode-0.2.1.vsix.zip](https://github.com/fudgepop01/kaitai_ide_vscode/files/3365240/kaitai-struct-vscode-0.2.1.vsix.zip)

The file opens fine on my end, so I added some debugging statements in the relevant functions to see if I can properly diagnose the issue.

**Comment by fridtjof** [comment]
Resizing the window did not do anything, but lowering the "bytes per line" value (to 8) made a total of 32 0x00 bytes appear.

When I look at the webview console, there are no messages.
However, if I click "open file as hex" in the context menu again now, the file shows up in the hex editor correctly.

These messages appear:
<img width="800" alt="grafik" src="https://user-images.githubusercontent.com/2780577/60768249-29b05680-a0c3-11e9-88ef-755d8e928562.png">

regular dev console:
<img width="896" alt="grafik" src="https://user-images.githubusercontent.com/2780577/60768298-3df45380-a0c3-11e9-9acf-1ff56bb79870.png">


So this means that when the hex editor isn't already open, it fails to receive the file payload. (Maybe some kind of race condition or similar?)

**Comment by fudgepop01** [comment]
Oh ok - yeah when the hex editor isn't already open there is a bit of a race condition of sorts. Currently I tell it to try to open it but it takes a moment for it to receive the data from the CDN. Perhaps I could use an event in the hex editor component that says it's ready and such...

The stuff that appears in the logs are debugging statements I wrote. Everything seems to be in working order there, so that's good.

---

Anyway, thanks for your cooperation! I'm glad that the file is opening properly. For now just make sure the editor itself is open first! I'll get to the race condition thing shortly.

**Comment by fudgepop01** [comment]
...Turns out I already added the event and just needed to attach an eventlistener and the proper things to make it wait if it's not already loaded.

Bug fixed! 👍

**Comment by fridtjof** [comment]
Awesome, thank you!
