### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jtran** [fudgepop01/kaitai_ide_vscode#32]
I looked for a license for this repo in all the standard places, but I didn't see one. Can you add a license file? [GitHubs docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) may help. Thank you.

**Comment by fudgepop01** [comment]
Hello! Thank you very much for pointing that out. This was one of my first big projects so I wasn't quite aware of the standards at the time, but I'll update it shortly

**Comment by jtran** [comment]
Closed by 98e289726bf9456dd834c7ac18ff719d38a52942. Thank you.
